//home
export const LOAD_LIST_FILM_REQUEST = 'LOAD_LIST_FILM_REQUEST';
export const LOAD_LIST_FILM_SUCCESS = 'LOAD_LIST_FILM_SUCCESS';

export const LOAD_LIST_USER_REQUEST = 'LOAD_LIST_USER_REQUEST';
export const LOAD_LIST_USER_SUCCESS = 'LOAD_LIST_USER_SUCCESS';

export const LOAD_LOGIN_REQUEST = 'LOAD_LOGIN_REQUEST';
export const LOAD_LOGIN_SUCCESS = 'LOAD_LOGIN_SUCCESS';

export const UPDATE_SHOWALERT = 'UPDATE_SHOWALERT';

export const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING'
export const UPDATE_ALERT = 'UPDATE_ALERT'


export const UPLOAD_FILE_LOADING = 'UPLOAD_FILE_LOADING';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';

export const LOAD_FIND_FILM_REQUEST = 'LOAD_FIND_FILM_REQUEST'
export const LOAD_FIND_FILM_SUCCESS = 'LOAD_FIND_FILM_SUCCESS'

export const LOAD_ADD_FILM_REQUEST = 'LOAD_ADD_FILM_REQUEST'
export const LOAD_ADD_FIM_SUCCESS = 'LOAD_ADD_FIM_SUCCESS'

export const LOAD_DELETE_FIM_REQUEST = 'LOAD_DELETE_FIM_REQUEST'
export const LOAD_DELETE_FILM_SUCCESS = 'LOAD_DELETE_FILM_SUCCESS'

export const LOAD_LIST_FILM_DELETE_REQUEST = 'LOAD_LIST_FILM_DELETE_REQUEST'
export const LOAD_LIST_FILM_DELETE_SUCCESS = 'LOAD_LIST_FILM_DELETE_SUCCESS'


export const DESTROY_SESSION = 'DESTROY_SESSION';