//home
export const LOAD_LIST_FILM_REQUEST = 'LOAD_LIST_FILM_REQUEST';
export const LOAD_LIST_FILM_SUCCESS = 'LOAD_LIST_FILM_SUCCESS';

export const LOAD_LIST_USER_REQUEST = 'LOAD_LIST_USER_REQUEST';
export const LOAD_LIST_USER_SUCCESS = 'LOAD_LIST_USER_SUCCESS';

export const LOAD_LOGIN_REQUEST = 'LOAD_LOGIN_REQUEST';
export const LOAD_LOGIN_SUCCESS = 'LOAD_LOGIN_SUCCESS';

export const UPDATE_SHOWALERT = 'UPDATE_SHOWALERT';

export const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING'
export const UPDATE_ALERT = 'UPDATE_ALERT'


export const UPLOAD_FILE_LOADING = 'UPLOAD_FILE_LOADING';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';


//tim kiem phim
export const LOAD_FIND_FILM_REQUEST = 'LOAD_FIND_FILM_REQUEST'
export const LOAD_FIND_FILM_SUCCESS = 'LOAD_FIND_FILM_SUCCESS'
export const UPDATE_LIST_FIND = 'UPDATE_LIST_FIND'


export const CREATE_FILM_REQUEST = 'CREATE_FILM_REQUEST'
export const CREATE_FILM_SUCCESS = 'CREATE_FILM_SUCCESS'

export const GET_LIST_FILM_DELETED_REQUEST = 'GET_LIST_FILM_DELETED_REQUEST'
export const LOAD_DELETE_FILM_SUCCESS = 'LOAD_DELETE_FILM_SUCCESS'

export const LOAD_LIST_FILM_DELETE_REQUEST = 'LOAD_LIST_FILM_DELETE_REQUEST'
export const LOAD_LIST_FILM_DELETE_SUCCESS = 'LOAD_LIST_FILM_DELETE_SUCCESS'

export const LOAD_RESTORE_REQUEST = 'LOAD_RESTORE_REQUEST'
export const LOAD_RESTORE_SUCCESS = 'LOAD_RESTORE_SUCCESS'

//page film
export const GET_LIST_FILM_REQUEST = 'GET_LIST_FILM_REQUEST'
export const GET_LIST_FILM_SUCCESS = 'GET_LIST_FILM_SUCCESS'
export const UPDATE_LOADING_LIST_FILM = 'UPDATE_LOADING_LIST_FILM'
export const UPDATE_REFRESHING_LIST_FILM = 'UPDATE_REFRESHING_LIST_FILM'

//Detail film
export const DETAIL_FILM_REQUEST = 'DETAIL_FILM_REQUEST'
export const DETAIL_FILM_SUCCESS = 'DETAIL_FILM_SUCCESS'    

// update restore
export const REMOVE_LISTFILM_DEDETED_REQUEST = 'REMOVE_LISTFILM_DEDETED_REQUEST'
export const REMOVE_LISTFILM_DEDETED_SUCCESS = 'REMOVE_LISTFILM_DEDETED_SUCCESS'
export const REMOVE_LISTFILM_DELETED = 'UPDATE_RESTORE'

//update listFilm after delete
export const UPDATE_REMOVE_DELETED_LISTFIM_REQUEST = 'UPDATE_REMOVE_DELETED_LISTFIM_REQUEST'
export const UPDATE_REMOVE_DELETED_LISTFIM_SUCCESS = 'UPDATE_REMOVE_DELETED_LISTFIM_SUCCESS'
export const UPDATE_REMOVE_DELETED_LISTFILM = ' UPDATE_REMOVE_DELETED_LISTFILM'

export const DESTROY_SESSION = 'DESTROY_SESSION';



//film deleted
export const LOAD_DELETE_FIM_REQUEST = 'LOAD_DELETE_FIM_REQUEST';
export const LOAD_LIST_FILM_ADMIN_REQUEST = 'LOAD_LIST_FILM_ADMIN_REQUEST';

//admin xoa phim -> danh sach phim da xoa + update UI
export const ADD_ITEM_FILM_LIST_EXITS = 'ADD_ITEM_FILM_LIST_EXITS'
export const ADD_ITEM_LIST_DELETD = 'ADD_ITEM_LIST_DELETD'
export const REMOVE_ITEM_FILM_EXITS = 'REMOVE_ITEM_FILM_EXITS'
export const REMOVE_ITEM_LIST_DELETED = 'REMOVE_ITEM_LIST_DELETED'

